<?php 
/*
Plugin Name: time-table
Plugin URI: http:myplugin.com
Description: My plugin
Version: 0.0.0.1
Author: Begunets S.A.
Author URI: http:myplugin.com
Text Domain: tt
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}

register_activation_hook(__FILE__, options_install);